#!/bin/bash
FILE_PATH="${TRIM_APPDEST}/docker/docker-compose.yaml"

is_docker_running() {
    local docker_name=""
    if [ -f "$FILE_PATH" ]; then
        docker_name=$(grep "container_name" "$FILE_PATH" | awk -F ':' '{print $2}' | xargs)
    fi
    if [ -n "$docker_name" ]; then
        docker inspect "$docker_name" | grep -q '"Status": "running",' || exit 1
        return
    fi
    exit 1
}

case "$1" in
start) exit 0 ;;
stop) exit 0 ;;
status) if is_docker_running; then exit 0; else exit 3; fi ;;
*) exit 1 ;;
esac
