version: '3.8'

services:
  daemon:
    image: docker.mslmc.cn/xiaoyululu/mslx-daemon:latest
    container_name: mslx-daemon
    restart: unless-stopped
    
    ports:
      - "${TRIM_SERVICE_PORT}:1027"
      - "25565-25585:25565-25585/tcp"
      - "25565-25585:25565-25585/udp"
      - "19132-19142:19132-19142/udp"
      
    extra_hosts:
      - "host.mslx.internal:host-gateway"
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TRIM_DATA_SHARE_PATHS}:/app/DaemonData
    
    environment:
      - TZ=Asia/Shanghai
      - IS_FNOS_APP=true
